# TCL File Generated by Component Editor 16.1
# Tue Sep 03 10:29:12 BRT 2019
# DO NOT MODIFY


# 
# LCD "LCD" v1.0
#  2019.09.03.10:29:12
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LCD
# 
set_module_property DESCRIPTION ""
set_module_property NAME LCD
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME LCD
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lcd
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file lcd.v VERILOG PATH verilogFiles/lcd.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab datab Input 32
add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1


# 
# connection point rw
# 
add_interface rw conduit end
set_interface_property rw associatedClock ""
set_interface_property rw associatedReset ""
set_interface_property rw ENABLED true
set_interface_property rw EXPORT_OF ""
set_interface_property rw PORT_NAME_MAP ""
set_interface_property rw CMSIS_SVD_VARIABLES ""
set_interface_property rw SVD_ADDRESS_GROUP ""

add_interface_port rw rw writeresponsevalid_n Output 1


# 
# connection point rs
# 
add_interface rs conduit end
set_interface_property rs associatedClock ""
set_interface_property rs associatedReset ""
set_interface_property rs ENABLED true
set_interface_property rs EXPORT_OF ""
set_interface_property rs PORT_NAME_MAP ""
set_interface_property rs CMSIS_SVD_VARIABLES ""
set_interface_property rs SVD_ADDRESS_GROUP ""

add_interface_port rs rs writeresponsevalid_n Output 1


# 
# connection point en
# 
add_interface en conduit end
set_interface_property en associatedClock ""
set_interface_property en associatedReset ""
set_interface_property en ENABLED true
set_interface_property en EXPORT_OF ""
set_interface_property en PORT_NAME_MAP ""
set_interface_property en CMSIS_SVD_VARIABLES ""
set_interface_property en SVD_ADDRESS_GROUP ""

add_interface_port en en writeresponsevalid_n Output 1


# 
# connection point display
# 
add_interface display conduit end
set_interface_property display associatedClock ""
set_interface_property display associatedReset ""
set_interface_property display ENABLED true
set_interface_property display EXPORT_OF ""
set_interface_property display PORT_NAME_MAP ""
set_interface_property display CMSIS_SVD_VARIABLES ""
set_interface_property display SVD_ADDRESS_GROUP ""

add_interface_port display display readdata Output 8

