// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 203 01/18/2017)
// Created on Thu Aug 22 10:09:16 2019

printBar printBar_inst
(
	.clk_in(clk_in_sig) ,	// input  clk_in_sig
	.clk_en(clk_en_sig) ,	// input  clk_en_sig
	.i_rst(i_rst_sig) ,	// input  i_rst_sig
	.o_active(o_active_sig) ,	// input  o_active_sig
	.o_x(o_x_sig) ,	// input [10:0] o_x_sig
	.o_y(o_y_sig) ,	// input [9:0] o_y_sig
	.coordY(coordY_sig) ,	// input [9:0] coordY_sig
	.color(color_sig) 	// output  color_sig
);

defparam printBar_inst.y_barraInicial = 285;
