# TCL File Generated by Component Editor 16.1
# Thu Aug 15 15:02:14 BRT 2019
# DO NOT MODIFY


# 
# VGA "VGA" v1.0
#  2019.08.15.15:02:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module VGA
# 
set_module_property DESCRIPTION ""
set_module_property NAME VGA
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME VGA
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga800x600
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga800x600.v VERILOG PATH assemblyCode/vga800x600.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga800x600
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file top.v VERILOG PATH assemblyCode/top.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave i_clk clk Input 1
add_interface_port nios_custom_instruction_slave i_rst reset Input 1


# 
# connection point o_y
# 
add_interface o_y conduit end
set_interface_property o_y associatedClock ""
set_interface_property o_y associatedReset ""
set_interface_property o_y ENABLED true
set_interface_property o_y EXPORT_OF ""
set_interface_property o_y PORT_NAME_MAP ""
set_interface_property o_y CMSIS_SVD_VARIABLES ""
set_interface_property o_y SVD_ADDRESS_GROUP ""

add_interface_port o_y o_y readdata Output 10


# 
# connection point o_x
# 
add_interface o_x conduit end
set_interface_property o_x associatedClock ""
set_interface_property o_x associatedReset ""
set_interface_property o_x ENABLED true
set_interface_property o_x EXPORT_OF ""
set_interface_property o_x PORT_NAME_MAP ""
set_interface_property o_x CMSIS_SVD_VARIABLES ""
set_interface_property o_x SVD_ADDRESS_GROUP ""

add_interface_port o_x o_x readdata Output 11


# 
# connection point o_animate
# 
add_interface o_animate conduit end
set_interface_property o_animate associatedClock ""
set_interface_property o_animate associatedReset ""
set_interface_property o_animate ENABLED true
set_interface_property o_animate EXPORT_OF ""
set_interface_property o_animate PORT_NAME_MAP ""
set_interface_property o_animate CMSIS_SVD_VARIABLES ""
set_interface_property o_animate SVD_ADDRESS_GROUP ""

add_interface_port o_animate o_animate writeresponsevalid_n Output 1


# 
# connection point o_screenend
# 
add_interface o_screenend conduit end
set_interface_property o_screenend associatedClock ""
set_interface_property o_screenend associatedReset ""
set_interface_property o_screenend ENABLED true
set_interface_property o_screenend EXPORT_OF ""
set_interface_property o_screenend PORT_NAME_MAP ""
set_interface_property o_screenend CMSIS_SVD_VARIABLES ""
set_interface_property o_screenend SVD_ADDRESS_GROUP ""

add_interface_port o_screenend o_screenend writeresponsevalid_n Output 1


# 
# connection point o_active
# 
add_interface o_active conduit end
set_interface_property o_active associatedClock ""
set_interface_property o_active associatedReset ""
set_interface_property o_active ENABLED true
set_interface_property o_active EXPORT_OF ""
set_interface_property o_active PORT_NAME_MAP ""
set_interface_property o_active CMSIS_SVD_VARIABLES ""
set_interface_property o_active SVD_ADDRESS_GROUP ""

add_interface_port o_active o_active writeresponsevalid_n Output 1


# 
# connection point o_vs
# 
add_interface o_vs conduit end
set_interface_property o_vs associatedClock ""
set_interface_property o_vs associatedReset ""
set_interface_property o_vs ENABLED true
set_interface_property o_vs EXPORT_OF ""
set_interface_property o_vs PORT_NAME_MAP ""
set_interface_property o_vs CMSIS_SVD_VARIABLES ""
set_interface_property o_vs SVD_ADDRESS_GROUP ""

add_interface_port o_vs o_vs writeresponsevalid_n Output 1


# 
# connection point o_hs
# 
add_interface o_hs conduit end
set_interface_property o_hs associatedClock ""
set_interface_property o_hs associatedReset ""
set_interface_property o_hs ENABLED true
set_interface_property o_hs EXPORT_OF ""
set_interface_property o_hs PORT_NAME_MAP ""
set_interface_property o_hs CMSIS_SVD_VARIABLES ""
set_interface_property o_hs SVD_ADDRESS_GROUP ""

add_interface_port o_hs o_hs writeresponsevalid_n Output 1


# 
# connection point o_blanking
# 
add_interface o_blanking conduit end
set_interface_property o_blanking associatedClock ""
set_interface_property o_blanking associatedReset ""
set_interface_property o_blanking ENABLED true
set_interface_property o_blanking EXPORT_OF ""
set_interface_property o_blanking PORT_NAME_MAP ""
set_interface_property o_blanking CMSIS_SVD_VARIABLES ""
set_interface_property o_blanking SVD_ADDRESS_GROUP ""

add_interface_port o_blanking o_blanking writeresponsevalid_n Output 1

